POST http://localhost:3000/api/users
Content-Type: application/json

{
  "user_id": "aerozedits@gmail.com",
  "email": "aerozedits@gmail.com",
  "photo": "https://avatars.githubusercontent.com/u/118265607?v=4",
  "firstname": "Fernando",
  "lastname": "Mariño",
  "bootcamp": "Full-Stak",
  "curse": "23-04",
  "github": "https://github.com/aerozfx"
}

###

PUT http://localhost:3000/api/users
Content-Type: application/json

{
  "user_id": "aerozedits@gmail.com",
  "email": "aerozedits@gmail.com",
  "photo": "https://avatars.githubusercontent.com/u/118265607?v=4",
  "firstname": "Chuck",
  "lastname": "Norris",
  "bootcamp": "Full-Stak",
  "curse": "23-04",
  "github": "https://github.com/aerozfx"
}

###

DELETE http://localhost:3000/api/users
Content-Type: application/json

{
  "user_id": "aerozedits@gmail.com"
}